# src/llm_consistency/data/schema.py
"""
Core domain models for the LLM consistency project.
These are lightweight data containers used in pipeline stages.
"""

from dataclasses import dataclass, asdict
from typing import Optional, Any, Dict, List
from enum import Enum
import pandas as pd


# ============================================================================
# ENUMS
# ============================================================================

class QuestionSubset(Enum):
    """Question subset options for answer generation."""
    ORIGINAL_ONLY = "original_only"
    PARAPHRASED_ONLY = "paraphrased_only"
    BOTH = "both"


class EvaluationLabel(Enum):
    """Standard evaluation labels across different evaluation types."""
    CORRECT = "correct"
    INCORRECT = "incorrect"
    NOT_ATTEMPTED = "not_attempted"
    
    @classmethod
    def from_letter(cls, letter: str) -> "EvaluationLabel":
        """Convert A/B/C to semantic labels."""
        mapping = {"A": cls.CORRECT, "B": cls.INCORRECT, "C": cls.NOT_ATTEMPTED}
        return mapping.get(letter.upper(), cls.NOT_ATTEMPTED)


# ============================================================================
# CORE ENTITIES
# ============================================================================

@dataclass
class Question:
    """A question from a dataset."""
    idx: int
    text: str
    dataset: str
    ground_truth: Optional[str] = None  # Answer or solution
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> dict:
        return asdict(self)
    
    @classmethod
    def from_series(cls, row: pd.Series, dataset: str, question_col: str, 
                    answer_col: Optional[str] = None) -> "Question":
        """Create Question from pandas Series."""
        return cls(
            idx=int(row.name) if row.name is not None else int(row.get("idx", 0)),
            text=row[question_col],
            dataset=dataset,
            ground_truth=row.get(answer_col) if answer_col else None,
            metadata=row.to_dict()
        )


@dataclass
class Paraphrase:
    """A paraphrased version of a question."""
    original_idx: int
    original_text: str
    paraphrased_text: str
    method: str  # "plain" or "toned"
    tip_or_tone: Optional[str] = None
    validation_score: Optional[float] = None
    
    def to_dict(self) -> dict:
        return {
            "idx": self.original_idx,
            "original_question": self.original_text,
            "paraphrased_question": self.paraphrased_text,
            "type": self.method,
            "tip_or_tone": self.tip_or_tone,
        }
    
    @classmethod
    def from_series(cls, row: pd.Series) -> "Paraphrase":
        """Create Paraphrase from pandas Series."""
        return cls(
            original_idx=int(row["idx"]),
            original_text=row["original_question"],
            paraphrased_text=row["paraphrased_question"],
            method=row.get("type", "unknown"),
            tip_or_tone=row.get("tip_or_tone"),
        )


@dataclass
class Answer:
    """An answer generated by a model."""
    question_idx: int
    original_question: str
    paraphrased_question: str
    model: str
    text: str
    temperature: float = 0.0
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> dict:
        base = {
            "idx": self.question_idx,
            "original_question": self.original_question,
            "paraphrased_question": self.paraphrased_question,
            "model": self.model,
            "answer": self.text,
        }
        if self.metadata:
            base.update(self.metadata)
        return base
    
    @classmethod
    def from_series(cls, row: pd.Series) -> "Answer":
        """Create Answer from pandas Series."""
        return cls(
            question_idx=int(row["idx"]),
            original_question=row["original_question"],
            paraphrased_question=row["paraphrased_question"],
            model=row["model"],
            text=row["answer"],
            temperature=row.get("temperature", 0.0),
        )


@dataclass
class Evaluation:
    """Result of evaluating an answer."""
    answer_idx: int  # Links back to the answer (DataFrame row index)
    question_idx: int
    model: str
    evaluator: str  # Name of the evaluator used
    label: EvaluationLabel
    score: Optional[float] = None  # Confidence or similarity score
    extracted_value: Optional[Any] = None  # e.g., normalized math answer
    raw_response: Optional[str] = None  # Full evaluator response
    
    # Optional fields for verbose storage (reliable joining)
    original_question: Optional[str] = None
    paraphrased_question: Optional[str] = None
    answer_text: Optional[str] = None
    ground_truth: Optional[str] = None
    
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self, verbose: bool = False) -> dict:
        """
        Convert to dictionary.
        
        Args:
            verbose: If True, include original_question, paraphrased_question, answer_text
        """
        result = {
            "answer_idx": self.answer_idx,
            "idx": self.question_idx,
            "model": self.model,
            "evaluator": self.evaluator,
            "verdict": self.label.value,
            "score": self.score,
            "extracted_value": self.extracted_value,
            "grading_response": self.raw_response,
        }
        
        # Add verbose fields if requested
        if verbose:
            if self.original_question is not None:
                result["original_question"] = self.original_question
            if self.paraphrased_question is not None:
                result["paraphrased_question"] = self.paraphrased_question
            if self.answer_text is not None:
                result["answer"] = self.answer_text
            if self.ground_truth is not None:
                result["ground_truth"] = self.ground_truth
        
        return result
    
    @classmethod
    def from_series(cls, row: pd.Series, evaluator: str) -> "Evaluation":
        """Create Evaluation from pandas Series."""
        # Handle verdict as string or EvaluationLabel
        verdict = row.get("verdict", "not_attempted")
        if isinstance(verdict, str):
            label = EvaluationLabel(verdict.lower())
        else:
            label = verdict
            
        return cls(
            answer_idx=int(row.name) if row.name is not None else 0,
            question_idx=int(row.get("idx", 0)),
            model=row.get("model", "unknown"),
            evaluator=evaluator,
            label=label,
            score=row.get("score"),
            extracted_value=row.get("extracted_value"),
            raw_response=row.get("grading_response"),
        )


@dataclass
class ConsistencyMetrics:
    """Aggregated consistency metrics for a question."""
    question_idx: int
    model: str
    num_variants: int  # Number of paraphrases
    
    # Label-based metrics
    label_entropy: Optional[float] = None
    label_distribution: Optional[Dict[str, float]] = None  # {label: proportion}
    majority_label: Optional[EvaluationLabel] = None
    agreement_rate: Optional[float] = None  # Proportion agreeing with majority
    
    # Value-based metrics (for math problems)
    value_distribution: Optional[Dict[Any, int]] = None  # {value: count}
    num_unique_values: Optional[int] = None
    
    # Semantic clustering metrics
    num_clusters: Optional[int] = None
    cluster_assignments: Optional[List[int]] = None
    semantic_entropy: Optional[float] = None
    
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> dict:
        result = {
            "idx": self.question_idx,
            "model": self.model,
            "num_variants": self.num_variants,
        }
        
        if self.label_distribution:
            result["label_distribution"] = self.label_distribution
        if self.majority_label:
            result["majority_label"] = self.majority_label.value
        if self.agreement_rate is not None:
            result["agreement_rate"] = self.agreement_rate
        if self.value_distribution:
            result["value_distribution"] = str(self.value_distribution)
        if self.num_unique_values is not None:
            result["num_unique_values"] = self.num_unique_values
        if self.num_clusters is not None:
            result["num_clusters"] = self.num_clusters
        if self.semantic_entropy is not None:
            result["semantic_entropy"] = self.semantic_entropy
            
        return result


# ============================================================================
# CONVERSION UTILITIES
# ============================================================================

def answers_to_df(answers: List[Answer]) -> pd.DataFrame:
    """Convert list of Answer objects to DataFrame."""
    return pd.DataFrame([a.to_dict() for a in answers])


def evaluations_to_df(evaluations: List[Evaluation], verbose: bool = False) -> pd.DataFrame:
    """
    Convert list of Evaluation objects to DataFrame.
    
    Args:
        evaluations: List of Evaluation objects
        verbose: If True, include original_question, paraphrased_question, answer fields
    """
    return pd.DataFrame([e.to_dict(verbose=verbose) for e in evaluations])


def df_to_answers(df: pd.DataFrame) -> List[Answer]:
    """Convert DataFrame to list of Answer objects."""
    return [Answer.from_series(row) for _, row in df.iterrows()]


def df_to_evaluations(df: pd.DataFrame, evaluator: str) -> List[Evaluation]:
    """Convert DataFrame to list of Evaluation objects."""
    return [Evaluation.from_series(row, evaluator) for _, row in df.iterrows()]